### ISSUE TITLE
work on articles categorization

### ISSUE THREAD

**Issue by mslovett21** [mslovett21/Bad_Press#28]

**Comment by sarahmathew** [comment]
I've done a kmeans analysis on td-idf vectors but I'm not sure how to find information from these points (like maybe their titles when we're hovering over the points)

I also did a LDA analysis, which I thought would be better because it finds different topics. The top topics I found didn't correspond to categories we care about- I'm thinking of removing the words for these irrelevant topics and looking for the next set of best topics

**Comment by sarahmathew** [comment]
next steps::

patrycja will find the hovering tool to better view the kmeans graphic

I will remove the words related to irrelevant topics
